<?xml version="1.0" encoding="utf-8"?><Database Name="Loja" Class="LojaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DEV-LENOVO;Initial Catalog=Loja;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="LojaConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Fabricante" Member="Fabricante">
    <Type Name="Fabricante">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descricao" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>